/**
 * Created by coatu on 2016/12/21.
 */

//用户
export const RECEIVE_LOGIN = "RECEIVE_LOGIN";//登录
export const RECEIVE_EXIT = "RECEIVE_EXIT";

export const RECEIVE_ISLOGIN = "RECEIVE_ISLOGIN";//是否登录

export const RECEIVE_DOMAIN = "RECEIVE_DOMAIN";//域名

export const RECEIVE_UPDATEUSERINFO = "RECEIVE_UPDATEUSERINFO";//更新用户info


export const RECEIVE_TABSWITCH = "RECEIVE_TABSWITCH";// 切换Tab
export const RECEIVE_JUMPPAGE = "RECEIVE_JUMPPAGE";//跳转页面
export const RECEIVE_ISTABSWITCH = "RECEIVE_ISTABSWITCH";//goBack 回来 。tab切换


//涂料大学
export const RECEIVE_SELECTCOATINGLABEL = "RECEIVE_SELECTCOATINGLABEL";//选中的Label
export const RECEIVE_SELECTCOATINGCHILDLABEL = "RECEIVE_SELECTCOATINGCHILDLABEL";//选中的子Label
export const RECEIVE_SELECTCOATINGCHILDLABELVALUE = "RECEIVE_SELECTCOATINGCHILDLABELVALUE";//值 转换选中的子Label
export const RECEIVE_COATINGLIST = "RECEIVE_COATINGLIST";//选中以后的列表
export const REQUIRE_COATINGLIST = "REQUIRE_COATINGLIST";//请求中的选中的列表
// export const RECEIVE_SELECTCOATINGLABEL = "RECEIVE_SELECTCOATINGLABEL";//选中的Label


//职位分级选择
export const RECEIVE_JOBCLASSIFY = 'RECEIVE_JOBCLASSIFY';//分级选择
export const RECEIVE_JOBCLASSIFYDATA = 'RECEIVE_JOBCLASSIFYDATA';//分级选择的所有数据
export const RECEIVE_JOBCLASSIFYSELECTED = 'RECEIVE_JOBCLASSIFYSELECTED';//传入分级已选择的
export const RECEIVE_JOBCLASSIFYISSPREAD = 'RECEIVE_JOBCLASSIFYISSPREAD';//当前级别展开或关闭  默认展开

/**
 * 涂友圈
 */
export const RECEIVE_DISCUSSLISTMESSAGE = 'RECEIVE_DISCUSSLISTMESSAGE';//列表分页
export const REQUIRE_DISCUSSLISTMESSAGE = 'REQUIRE_DISCUSSLISTMESSAGE';//请求列表分页
export const RECEIVE_DISCUSSOPTIONISSHOW = 'RECEIVE_DISCUSSOPTIONISSHOW';//操作点开

export const RECEIVE_DISCUSSDELETEMESSAGE = 'RECEIVE_DISCUSSDELETEMESSAGE';//删除信息 discuss/deleteMessage
export const RECEIVE_DISCUSSDELETECOMMENT = 'RECEIVE_DISCUSSDELETECOMMENT';//删除评论 discuss/deleteComment
export const RECEIVE_DISCUSSDELETELIKE = 'RECEIVE_DISCUSSDELETELIKE';//取消点赞 discuss/deleteLike
export const RECEIVE_DISCUSSSAVELIKE = 'RECEIVE_DISCUSSSAVELIKE';//点赞 discuss/saveLike
export const RECEIVE_DISCUSSSAVECOMMENT = 'RECEIVE_DISCUSSSAVECOMMENT';//评论（回复评论）discuss/saveComment
export const RECEIVE_DISCUSSSHAREREFRESH = 'RECEIVE_DISCUSSSHAREREFRESH';//是否有分享以后需要刷新
export const RECEIVE_DISCUSSSWITCHTAB = 'RECEIVE_DISCUSSSWITCHTAB';//发现切换Tab
export const RECEIVE_DISCUSSPAGEDISCUSSNOTICE = 'RECEIVE_DISCUSSPAGEDISCUSSNOTICE';//发现 通知消息 列表
export const RECEIVE_DISCUSSCLEARDISCUSSNOTICE = 'RECEIVE_DISCUSSCLEARDISCUSSNOTICE';//删除  通知消息 列表

export const RECEIVE_DISCUSSSAVECOMMENTLIKE= 'RECEIVE_DISCUSSSAVECOMMENTLIKE';//评论点赞 discuss/saveCommentLike
// export const RECEIVE_DISCUSSDELETECOMMENTLIKE = 'RECEIVE_DISCUSSDELETECOMMENTLIKE';//评论取消点赞 discuss/deleteCommentLike

export const RECEIVE_DISCUSSDETAILOPTION = 'RECEIVE_DISCUSSDETAILOPTION';//详情操作
export const RECEIVE_MYDISCUSSDETAILOPTION = 'RECEIVE_MYDISCUSSDETAILOPTION';//我的详情操作


//个人主页  给人发消息
export const RECEIVE_IMCHATSENDMSG = 'RECEIVE_IMCHATSENDMSG';
export const REQUEST_IMCHATSENDMSG = 'REQUEST_IMCHATSENDMSG';

export const RECEIVE_IMCHATMSGLIST = 'RECEIVE_IMCHATMSGLIST';//列表
export const REQUEST_IMCHATMSGLIST = 'REQUEST_IMCHATMSGLIST';
export const RECEIVE_IMCHATKEY = 'RECEIVE_IMCHATKEY';//当前聊天人保存一个key


//我的发布，想了想不是分开比较靠谱
export const RECEIVE_MYDISCUSSLISTMESSAGE = 'RECEIVE_MYDISCUSSLISTMESSAGE';//列表分页
export const REQUEST_MYDISCUSSLISTMESSAGE = 'REQUEST_MYDISCUSSLISTMESSAGE';//列表分页
export const RECEIVE_MYDISCUSSOPTIONISSHOW = 'RECEIVE_MYDISCUSSOPTIONISSHOW';//操作点开
export const RECEIVE_MYDISCUSSDELETEMESSAGE = 'RECEIVE_MYDISCUSSDELETEMESSAGE';//删除信息 discuss/deleteMessage
export const RECEIVE_MYDISCUSSDELETECOMMENT = 'RECEIVE_MYDISCUSSDELETECOMMENT';//删除评论 discuss/deleteComment

// export const RECEIVE_MYDISCUSSDELETELIKE = 'RECEIVE_MYDISCUSSDELETELIKE';//取消点赞 discuss/deleteLike
export const RECEIVE_MYDISCUSSSAVELIKE= 'RECEIVE_MYDISCUSSSAVELIKE';//点赞 discuss/saveLike
export const RECEIVE_MYDISCUSSSAVECOMMENTLIKE= 'RECEIVE_MYDISCUSSSAVECOMMENTLIKE';//评论点赞 discuss/saveCommentLike

export const RECEIVE_MYDISCUSSSAVECOMMENT= 'RECEIVE_MYDISCUSSSAVECOMMENT';//评论（回复评论）discuss/saveComment

/**---用户数据    地址、发票等等--*/
export const RECEIVE_ADDRESSLIST = 'RECEIVE_ADDRESSLIST';//列表
export const REQUEST_ADDRESSLIST = 'REQUEST_ADDRESSLIST';//列表
//设置默认
export const RECEIVE_ISDEFAULT = 'RECEIVE_ISDEFAULT';
export const REQUEST_ISDEFAULT = 'REQUEST_ISDEFAULT';
//设置删除
export const RECEIVE_DELADDRESS = 'RECEIVE_DELADDRESS';
export const REQUEST_DELADDRESS = 'REQUEST_DELADDRESS';
//设置添加新地址
export const RECEIVE_NEWADDRESS = 'RECEIVE_NEWADDRESS';
export const REQUEST_NEWADDRESS = 'REQUEST_NEWADDRESS';
//设置编辑地址
export const RECEIVE_EditADDRESS = 'RECEIVE_EditADDRESS';
export const REQUEST_EditADDRESS = 'REQUEST_EditADDRESS';
//发票列表
export const REQUEST_BillLIST = 'REQUEST_BillLIST';
export const RECEIVE_BillLIST = 'RECEIVE_BillLIST';
//设置默认发票
export const REQUEST_SETDEFAULTBILL = 'REQUEST_SETDEFAULTBILL';
export const RECEIVE_SETDEFAULTBILL = 'RECEIVE_SETDEFAULTBILL';
//发票详情展示
export const REQUEST_BILLSHOW = 'REQUEST_BILLSHOW';
export const GET_BILLSHOW = 'GET_BILLSHOW';
export const RECEIVE_BILLSHOW = 'RECEIVE_BILLSHOW';


//分类详情 现在的。
export const RECEIVE_TYPEHEAD = 'RECEIVE_TYPEHEAD';
export const RECEIVE_TYPELEFT = 'RECEIVE_TYPELEFT';
export const REQUEST_TYPELEFT = 'REQUEST_TYPELEFT';
export const RECEIVE_TYPERIGHT = 'RECEIVE_TYPERIGHT';
export const RECEIVE_TYPECLEAR = 'RECEIVE_TYPECLEAR';

//分类详情 以前的
export const RECEIVE_TYPEDETAIL = 'RECEIVE_TYPEDETAIL';
export const REQUEST_TYPEDETAIL = 'REQUEST_TYPEDETAIL';

export const RECEIVE_TYPERIGHTDETAIL = 'RECEIVE_TYPERIGHTDETAIL';


/**------------购物车---*/
//购物车列表
export const RECEIVE_SHOPLIST = 'RECEIVE_SHOPLIST';
export const REQUEST_SHOPLIST = 'REQUEST_SHOPLIST';
//删除购物车
export const RECEIVE_SHOPDELETE = 'RECEIVE_SHOPDELETE';
export const REQUEST_SHOPDELETE = 'REQUEST_SHOPDELETE';
//购物车数量减少
export const RECEIVE_SHOPREDUCE = 'RECEIVE_SHOPREDUCE';
//购物车数量增加
export const RECEIVE_SHOPRADD = 'RECEIVE_SHOPRADD';
//购物车总数
export const RECEIVE_SHOPCOUNT = 'RECEIVE_SHOPCOUNT';
//购物车总价格
export const RECEIVE_TOTALPRICE = 'RECEIVE_TOTALPRICE';
//选中购物车
export const RECEIVE_SELECTSHOPCART = 'RECEIVE_SELECTSHOPCART';
//清理选中
export const RECEIVE_CLEARSELECTSHOPCART = 'RECEIVE_CLEARSELECTSHOPCART';
//加入购物车
export const RECEIVE_ADDSHOP = 'RECEIVE_ADDSHOP';
export const REQUEST_ADDSHOP = 'REQUEST_ADDSHOP';

//清空选中的购物车
export const RECEIVE_CLEARSELECTSHOP = 'RECEIVE_CLEARSELECTSHOP';

//购物车总计
export const RECEIVE_ALLMONEY = 'receive_allmoney';
//选中的购物车产品id
export const RECEIVE_SELECTID = 'receive_selectid';
//选中的购物车产品id及数量
export const RECEIVE_SELECTDATA = 'Receive_SelectData';
//选中总价格
export const RECEIVE_TOTALPRIVE = 'receive_totalprive';

//选择优惠券
export const RECEIVE_SELECTCOUPON = "RECEIVE_SELECTCOUPON";//选择
export const RECEIVE_LISTCOUPON = "RECEIVE_LISTCOUPON";//列表
export const REQUESR_LISTCOUPON = "REQUESR_LISTCOUPON";//列表--
export const RECEIVE_DEFAULTCOUPON = "RECEIVE_DEFAULTCOUPON";//选中的默认
export const RESET_COUPONDATA = "reset_coupondata";//重置

/*找产品*/

//推荐品牌
export const RECEIVE_BRAND = 'RECEIVE_BRAND';
export const REQUEST_BRAND = 'REQUEST_BRAND';
//图片轮播
export const RECEIVE_IMAGEBANNER = 'RECEIVE_IMAGEBANNER';
export const REQUESR_IMAGEBANNER = 'REQUESR_IMAGEBANNER';
//推荐产品
export const RECEIVE_PRODUCT = 'RECEIVE_PRODUCT';
export const REQUEST_PRODUCT = 'REQUEST_PRODUCT';
//收藏产品
export const RECEIVE_COLLECTPRODUCT = 'RECEIVE_COLLECTPRODUCT';
export const REQUEST_COLLECTPRODUCT = 'REQUEST_COLLECTPRODUCT';
//回调产品是否收藏
export const RECEIVE_COLLECTPRODUCTID = 'RECEIVE_COLLECTPRODUCTID';
export const REQUEST_COLLECTPRODUCTID = 'REQUEST_COLLECTPRODUCTID';
//产品收藏总数
export const RECEIVE_COLLECTPRODUCTCOUNT = 'RECEIVE_COLLECTPRODUCTCOUNT';
export const REQUEST_COLLECTPRODUCTCOUNT = 'REQUEST_COLLECTPRODUCTCOUNT';
//产品收藏列表
export const RECEIVE_COLLECTPRODUCTLIST = 'RECEIVE_COLLECTPRODUCTLIST';
export const REQUEST_COLLECTPRODUCTLIST = 'REQUEST_COLLECTPRODUCTLIST';
//收藏列表clear数据
export const RECEIVE_CLEARCOLLECTPRODUCTLIST = 'RECEIVE_CLEARCOLLECTPRODUCTLIST';


/*首页*/
export const RECEIVE_HOMELIST = 'RECEIVE_HOMELIST';
export const REQUEST_HOMELIST = 'REQUEST_HOMELIST';
export const RECEIVE_HOMEMYLIST = 'RECEIVE_HOMEMYLIST'; //首页我的列表
export const REQUEST_HOMEMYLIST = 'REQUEST_HOMEMYLIST';//首页我的列表


/*我的积分*/
export const RECEIVE_MYSCORE = 'RECEIVE_MYSCORE';
/*我的专家分*/
export const RECEIVE_MYEXPERTSCORE = 'RECEIVE_MYEXPERTSCORE';
/*我的消息*/
export const RECEIVE_MEMESSAGE = 'RECEIVE_MEMESSAGE';
//我的订单
export const RECEIVE_MEORDER = 'RECEIVE_MEORDER';
//我的关注
export const RECEIVE_FOLLOW = 'RECEIVE_FOLLOW';
export const RECEIVE_FOLLOWSELECT = 'RECEIVE_FOLLOWSELECT';//选择关注

//问题列表
export const RECEIVE_QUESTLIST = 'RECEIVE_QUESTLIST';
export const REQUEST_QUESTLIST = 'REQUEST_QUESTLIST';

//向我提问
export const RECEIVE_ASKQUESTLIST = 'RECEIVE_ASKQUESTLIST';
export const REQUEST_ASKQUESTLIST = 'REQUEST_ASKQUESTLIST';

//热门问题

export const RECEIVE_HOTQUESTLIST = 'RECEIVE_HOTQUESTLIST';
export const REQUEST_HOTQUESTLIST = 'REQUEST_HOTQUESTLIST';

//发布
export const RECEIVE_FABU = 'RECEIVE_FABU';

//评论详情
export const RECEIVE_COMMENTDETAILLIST = 'RECEIVE_COMMENTDETAILLIST';
export const REQUEST_COMMENTDETAILLIST = 'REQUEST_COMMENTDETAILLIST';

//所有认证用户列表
export const RECEIVE_LISTALLCERTIFIEDUSER = 'RECEIVE_LISTALLCERTIFIEDUSER';
export const RECEIVE_CERTIFIEDUSERSELECT = 'RECEIVE_CERTIFIEDUSERSELECT';


//主页 大学 选中的label
export const RECEIVE_SELECTEDLABEL = 'RECEIVE_SELECTEDLABEL';
export const REQUEST_SELECTEDLABEL = 'REQUEST_SELECTEDLABEL';
//推荐品牌
export const RECEIVE_HOMERECOMMEND = 'RECEIVE_HOMERECOMMEND';
export const REQUEST_HOMERECOMMEND = 'REQUEST_HOMERECOMMEND';

//主页是否关注的按钮状态
export const RECEIVE_HOMEFOLLOW = 'RECEIVE_HOMEFOLLOW';

//重新登录大学数据不刷新的状态
export const RECEIVE_LOGINTECHNICAL = 'RECEIVE_LOGINTECHNICAL';

//注册职位
export const RECEIVE_RADIO = 'RECEIVE_RADIO';
export const RECEIVE_MULTISELECT = 'RECEIVE_MULTISELECT';
export const RECEIVE_SETCHECKDATA = 'RECEIVE_SETCHECKDATA';
export const RECEIVE_SETCHECKTEXTDATA = 'RECEIVE_SETCHECKTEXTDATA';


//导航条图片
export const RECEIVE_NAVSELECTEDIMAGE = 'RECEIVE_NAVSELECTEDIMAGE';

export const RECEIVE_SENDMESSAGE = 'RECEIVE_SENDMESSAGE';//发送消息给客服
export const REQUEST_SENDMESSAGE = 'REQUEST_SENDMESSAGE';

export const RECEIVE_MESSAGELIST = 'RECEIVE_MESSAGELIST';//列表
export const REQUEST_MESSAGELIST = 'REQUEST_MESSAGELIST';

//收藏列表
export const RECEIVE_ARTICLECOLLECTLIST = 'RECEIVE_ARTICLECOLLECTLIST';
export const RECEIVE_ISCOLLECTARTICLE = 'RECEIVE_ISCOLLECTARTICLE';
export const RECEIVE_DELETEARTICLECOLLECTLIST = 'RECEIVE_DELETEARTICLECOLLECTLIST';
//Home列表
export const receive_home11 = 'receive_home11';
export const request_home11 = 'request_home11';




