/**
 * Created by coatu on 2017/8/21.
 */
const Imgs = {
    //tabBar/navbar
    back: require('../imgs/navigator/back_btn.png'),
    back_btn: require('../imgs/navigator/back_btn.png'),
    right_arrow: require('../imgs/other/right_arrow.png'),
    close: require('../imgs/other/close.png'),
    favorite: require('../imgs/navigator/favorite.png'),
    favoriteSel: require('../imgs/navigator/favoriteSel.png'),
    findProduct: require('../imgs/navigator/findProduct.png'),
    findProductSel: require('../imgs/navigator/findProductSel.png'),
    home: require('../imgs/navigator/home.png'),
    homeSel: require('../imgs/navigator/homeSelected.png'),
    interlocutionCircle: require('../imgs/navigator/ask.png'),
    discussDefaultHead: require('../imgs/discuss/discuss_default_head.png'),
    discussAuthentication: require('../imgs/discuss/authentication.png'),
    discussCircle: require('../imgs/navigator/discuss_icon.png'),
    defaultImage: require('../imgs/home/defaultImage.png'),
    search_btn: require('../imgs/navigator/search_btn.png'),
    shoping: require('../imgs/navigator/shoping.png'),
    shopingSel: require('../imgs/navigator/shopingSel.png'),
    universitySel: require('../imgs/navigator/university_red.png'),
    university: require('../imgs/navigator/university_white.png'),
    mine: require('../imgs/navigator/user.png'),
    mineSel: require('../imgs/navigator/userSel.png'),
    mineCamero: require('../imgs/me/camera.png'),
    mineBg: require('../imgs/me/mineBg.png'),
    mineSignIcon: require('../imgs/me/sign_icon.png'),
    mineModify: require('../imgs/me/modify.png'),
    shareIcon: require('../imgs/me/share.png'),
    signBigImg: require('../imgs/me/sign_big_bg.png'),
    scoreSmallImg: require('../imgs/me/sign_small_bg.png'),
    replay: require('../imgs/problem/replay.png'),
    replayEdit: require('../imgs/problem/reply.png'),
    defaultAvatar: require('../imgs/home/defaultVipAvatar.png'),
    articleDefaultImage: require('../imgs/home/defaultImage.png'),
    proDefaultImage: require('../imgs/other/defaultimg.png'),
    userQuiz: require('../imgs/problem/userQuiz.png'),
    // customQuiz: require('../imgs/problem/customQuiz.png'),
    checkSel: require('../imgs/checked_50px.png'),
    checkUnSel: require('../imgs/checked_gray_50px.png'),
    sortGrayDown: require('../imgs/find/Sort_Down_Gray_25px.png'),
    sortDown: require('../imgs/find/Sort_Down_25px.png'),
    sortUp: require('../imgs/find/Sort_Up_25px.png'),
};

export default Imgs;
